version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - '8050:8080'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
    environment:
      JENKINS_HOME: /var/jenkins_home
    networks:
      - jenkins-network
  node1:
    build:
      context: ./nodes/base-worker
      dockerfile: Dockerfile
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_AGENT_NAME: worker1-base
      JENKINS_SECRET: c68049c3b86ac8fb0d69b26472df3abdafa580377fb25ff696eef461748be100
    networks:
      - jenkins-network

  node2:
    build:
      context: ./nodes/pytest-worker
      dockerfile: Dockerfile
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_AGENT_NAME: worker2-python
      JENKINS_SECRET: 28b6f0e32b0f68858ffcc37f18d12806b699d5319708f17beed2ea432d363243
    networks:
      - jenkins-network

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-network:
